ALTER TABLE users ADD COLUMN ra VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN tag VARCHAR(255) UNIQUE;
ALTER TABLE users add fingerprint VARCHAR(255) UNIQUE;
ALTER TABLE users add group_id BIGINT;