ALTER TABLE users ADD COLUMN ra VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN tag VARCHAR(255) UNIQUE;
ALTER TABLE users add fingerprint VARCHAR(255) UNIQUE;
ALTER TABLE users add group_id BIGINT;
ALTER TABLE users add user_id BIGINT;
ALTER TABLE users ADD COLUMN dtcreate TIMESTAMP;
ALTER TABLE users ADD COLUMN dtupdate TIMESTAMP;

ALTER TABLE users ADD CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES groups(id);
ALTER TABLE users ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id);