# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build-mysql:
    
    runs-on: ubuntu-latest
    env:
          DATABASE: mysql
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql database: 'sphynx_api'
        mysql root password: 'root'
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Mysql Jar API
        path: target/sphynx-0.0.1-SNAPSHOT.jar
  build-mariadb:
    
    runs-on: ubuntu-latest
    env:
          DATABASE: mariadb
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop

    - name: Set up MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mariadb version: '10.4.10' 
        mysql database: 'sphynx_api'
        mysql root password: 'root'
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Mariadb Jar API
        path: target/sphynx-0.0.1-SNAPSHOT.jar
      
